### ISSUE TITLE
Any ideea?

### ISSUE THREAD

**Issue by fmohican** [Arnavion/libjass#96] opened 2017-07-25 18:41 UTC
Typesettig ins't work, i mean mask with gradient and karaoke effect.

video.min.js:1 VIDEOJS: ERROR: TypeError: Cannot read property 'appendItem' of undefined
    at e.toSVG (drawing-styles.ts:68)
    at r.preRender (renderer.ts:781)
    at r.draw (renderer.ts:882)
    at r.e.Me (null.ts:165)
    at r.Me (renderer.ts:986)
    at e.<anonymous> (null.ts:50)
    at e.be (base.ts:60)
    at e.tick (manual.ts:70)
    at e.seek (manual.ts:92)
    at e.seeking (auto.ts:89)
r.logByType @ video.min.js:1
s.error @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
c @ video.min.js:1
t.trigger @ video.min.js:1
e.handleTechSeeking_ @ video.min.js:1
o @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
seeking (async)
e.setCurrentTime @ video.min.js:1
e.techCall_ @ video.min.js:1
e.currentTime @ video.min.js:1
e.handleMouseMove @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
video.min.js:1 VIDEOJS: ERROR: TypeError: Cannot read property 'appendItem' of undefined
    at e.toSVG (drawing-styles.ts:68)
    at r.preRender (renderer.ts:781)
    at r.draw (renderer.ts:882)
    at r.e.Me (null.ts:165)
    at r.Me (renderer.ts:986)
    at e.<anonymous> (null.ts:50)
    at e.be (base.ts:60)
    at e.tick (manual.ts:70)
    at e.seek (manual.ts:92)
    at e.seeking (auto.ts:89)
r.logByType @ video.min.js:1
s.error @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
c @ video.min.js:1
t.trigger @ video.min.js:1
e.handleTechSeeking_ @ video.min.js:1
o @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
seeking (async)
e.setCurrentTime @ video.min.js:1
e.techCall_ @ video.min.js:1
e.currentTime @ video.min.js:1
e.handleMouseMove @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
video.min.js:1 VIDEOJS: ERROR: TypeError: Cannot read property 'appendItem' of undefined
    at e.toSVG (drawing-styles.ts:68)
    at r.preRender (renderer.ts:781)
    at r.e.Me (null.ts:169)
    at r.Me (renderer.ts:986)
    at e.<anonymous> (null.ts:50)
    at e.be (base.ts:60)
    at e.tick (manual.ts:70)
    at e.seek (manual.ts:92)
    at e.seeking (auto.ts:89)
    at e.<anonymous> (videojs.ass.js:55)
r.logByType @ video.min.js:1
s.error @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
c @ video.min.js:1
t.trigger @ video.min.js:1
e.handleTechSeeking_ @ video.min.js:1
o @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1
seeking (async)
e.setCurrentTime @ video.min.js:1
e.techCall_ @ video.min.js:1
e.currentTime @ video.min.js:1
e.handleMouseMove @ video.min.js:1
o @ video.min.js:1
n.dispatcher.n.dispatcher @ video.min.js:1

**Comment by Arnavion** [comment] 2017-07-25 18:58
Duplicate of #87

**Closed by Arnavion** 2017-07-25 18:58 UTC
