### ISSUE TITLE
Lines can be "pushed away" by other lines on the same layer

### ISSUE THREAD

**Issue by DoomTay** [Arnavion/libjass#98] opened 2017-08-07 05:56 UTC
An ASS file like this

```
[Script Info]
Title: English (US)
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 640
PlayResY: 360
Subtitle ID: 241911
Language: English (US)
Created: 2017-02-22 07:29:47

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: lefty,Arial,15,&H00FFFFFF,&H000000FF,&H004F6061,&H004F6061,0,0,0,0,100,100,0,0,1,0,1,7,0121,0370,0206,1
Style: righty,Arial,15,&H00FFFFFF,&H000000FF,&H004F6061,&H004F6061,0,0,0,0,100,100,0,0,1,0,1,7,0376,0020,0206,1

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.00,0:00:15.00,lefty,Text,0000,0000,0000,,I am the left
Dialogue: 0,0:00:00.00,0:00:15.00,righty,Text,0000,0000,0000,,and this is the right
```

will cause "righty" to be pushed out of frame when it and "lefty" should be next to each other.

**Comment by DoomTay** [comment] 2017-11-07 20:12
After some tinkering with HTML, I'm beginning to think setting the position of each "an group" to absolute might solve it

**Comment by Arnavion** [comment] 2017-11-07 20:34
Duplicate of #48

**Closed by Arnavion** 2017-11-07 20:34 UTC
